In [45]:
# Differencr b/w List and NumpyArrays
            # LIST.                        NumpuArrays
            # multiple datatype.           Element with same datatype.
            # Slow performance.            Much faster performance.(c-level)
            # Low memory efficiency.       High memory efficiency.

In [46]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [47]:
import numpy as np

Basic array creation

In [48]:
arr = np.array([1,2,3,4,5]) #creation of array

In [49]:
arr

array([1, 2, 3, 4, 5])

In [50]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [51]:
np.array(l1) #2d matrix i array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GEMERATION FUNCTIONS
np.arange(1,11) -> will create a array from 1 to 10
np.zeros(6) -> will generate arrays of zeros
np.linspace() -> will returns evenly soaced number over a interval

In [52]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [54]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
arr = np.linspace(0,100,1)
arr

array([0.])

RANDOM GENERATION FUNCTION
gives random numbers from 0 and 1 (normalisation)

In [56]:
np.random.randn(5)

array([-0.39864859,  2.30032344, -0.28532568,  0.3424766 , -0.91173371])

In [57]:
np.random.randint(1,100,5)

array([63, 27, 74, 35, 34])

ARRAY ATTRIBUTES
arr.shape -> gives no.of rows and colums
arr.size -> gives size of array
arr.dtype -> gives data type of array

In [58]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [59]:
arr.size

6

In [60]:
arr.dtype

dtype('int64')

ARRAY METHODS
arr.min() -> returns min element
arr.max() -> returns maximum element
arr.sum() -> gives sum of all elements
arr.mean() -> gives mean
arr.std() -> gives standard deviation

In [61]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr1.min()

1

In [63]:
arr1.max()

9

In [64]:
arr1.sum()

45

In [65]:
arr1.mean()

5.0

In [66]:
arr1.std()

2.581988897471611

RESHAPE AND RESIZE OF ARRAY

In [67]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [68]:
arr.reshape(5,6) #makes a vectorn in matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [69]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])